version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: stokolbas
      POSTGRES_USER: igsiggs
      POSTGRES_PASSWORD: R4OyHyWz
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://igsiggs:R4OyHyWz@db:5432/stokolbas
    volumes:
      - .:/app

volumes:
  pgdata: